#!/bin/sh

TARGET=$1
CERT=$2
KEY=$3
SCRIPT_HOME=`dirname $0`
if [ -e /env ]; then
  . /env
else
  export ENVIRONMENT=VAGRANT
fi

if [ "$ENVIRONMENT" = VAGRANT ]; then
  SERVER_IP=`cat /etc/hosts | grep openvpn | awk '{ print $1 }'`
else
  if [ -e "$SCRIPT_HOME"/ip.txt ]; then
    SERVER_IP=`cat "$SCRIPT_HOME"/ip.txt`
  else
    SERVER_IP=`curl -4 icanhazip.com`
    echo $SERVER_IP > "$SCRIPT_HOME"/ip.txt
  fi
fi
export SERVER_IP

sed "/<ca>/r rootCA.crt" client.ovpn.in | sed "/<cert>/r $CERT" | sed "/<key>/r $KEY" | sed s/SERVER-IP/${SERVER_IP}/g > $TARGET
