#!/bin/bash

if [ -z "$1" ]; then
	echo 'Usage: genkey <device-name>' 1>&2
	exit 1
fi

if ( echo "$1" | /usr/bin/grep '[^-a-z0-9_]' ) >/dev/null 2>&1 || [[ "$1" == -* ]]; then
        echo Invalid device-name 1>&2
        exit 1;
fi

/usr/bin/sudo $HOME/bin/genkey.root $1
